### ISSUE TITLE
Android: Remove background image?

### ISSUE THREAD

**Issue by Noitidart** [johniak/react-native-root-view-background#3]
I have created a background image in my Android using native technique, this is for splash screen. Like this:

https://medium.com/react-native-development/change-splash-screen-in-react-native-android-app-74e6622d699

This image stays in the background forever. When keyboard or switching views I sometimes see it. Do you have any ideas on how to remove it?

**Comment by Noitidart** [comment]
As we see, in this article to set splash, we set a background image in the same way you propose setting background color in your article - https://medium.com/@janromaniak/how-to-change-background-color-of-rootview-in-react-native-d1b67829a83a#01be

**Comment by johniak** [comment]
I see this two solution are not working together. In current state there is no way to this with react-native-root-view-background library, and you will need to write some native code
